### ISSUE TITLE
How ot blur "Desktop Folders" window-field on Desktop

### ISSUE THREAD

**Issue by Ygarr** [taj-ny/kwin-effects-forceblur#102]
The topic. I have on Desktop "Desktop Folders" widget with folders and files in it , it would be great to blur them also not only just transparent

**Comment by taj-ny** [comment]
Desktop widgets are not windows and therefore cannot be blurred by this effect. You'll need to find a plasma style that supports blur (System Settings -> Colors & Themes -> Plasma Style).
