### ISSUE TITLE
Not showing up under plasma desktop effects list

### ISSUE THREAD

**Issue by illnesse** [taj-ny/kwin-effects-forceblur#131]
kwin-effects-forceblur-git, rebuilding doesn't seem to help:

![image](https://github.com/user-attachments/assets/07c324b0-c134-47e7-9a02-923ccc6b82a5)
![image](https://github.com/user-attachments/assets/550d7250-bc4e-44ac-8542-0f56af17c8ae)
![image](https://github.com/user-attachments/assets/22c53922-3c63-4f5b-9de6-25d67f0687f7)

**Comment by D3SOX** [comment]
Just curious: Does the non-git version work?

**Comment by taj-ny** [comment]
Choose ``All`` when yay asks which packages to cleanBuild.
