### ISSUE TITLE
fake blur is broken

### ISSUE THREAD

**Issue by sf467** [taj-ny/kwin-effects-forceblur#150]
![图片](https://github.com/user-attachments/assets/a49238fd-37bb-4b52-9777-3713f6c3ab19)

**Comment by taj-ny** [comment]
What exactly do you mean by broken? The settings for fake blur in this version are in the General tab.

**Comment by sf467** [comment]
> 你所说的破损到底是什么意思？此版本中的假模糊设置位于“常规”选项卡中，您的图片并没有真正告诉我任何信息。

![图片](https://github.com/user-attachments/assets/e9bad098-9513-4174-880e-1c2c24c4e4d0)I mean, in the current version, only the content under the window can be blurred instead of the wallpaper

**Comment by taj-ny** [comment]
On the main branch the effect can automatically use your wallpaper.

![image](https://github.com/user-attachments/assets/a722e401-f4fd-4f45-822a-bbbf9384087d)

**Comment by sf467** [comment]
I use 1.3.4, and it from AUR
