### ISSUE TITLE
Build error openSUSE Tumbleweed

### ISSUE THREAD

**Issue by kaoxk27** [taj-ny/kwin-effects-forceblur#20]
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF6 (missing: Config ConfigWidgets Crash GlobalAccel I18n
  KIO Service Notifications Service WidgetsAddons GuiAddons KCMUtils) (found
  suitable version "6.0.0", minimum required is "5.240.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF6.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:42 (find_package)

**Comment by taj-ny** [comment]
Try this. I stole it from Klassy, so I'm not sure if that's going to work.
```sh
sudo zypper in git cmake extra-cmake-modules kcoreaddons-devel kguiaddons-devel kconfigwidgets-devel kwindowsystem-devel ki18n-devel kiconthemes-devel kpackage-devel frameworkintegration-devel kcmutils-devel kirigami2-devel
```

**Comment by Haraven** [comment]
> Try this. I stole it from Klassy, so I'm not sure if that's going to work.
> 
> ```shell
> sudo zypper in git cmake extra-cmake-modules kcoreaddons-devel kguiaddons-devel kconfigwidgets-devel kwindowsystem-devel ki18n-devel kiconthemes-devel kpackage-devel frameworkintegration-devel kcmutils-devel kirigami2-devel
> ```

Hey, I tried running the above command, but building still failed. I did get the build to work eventually. Besides running the above zypper command, what I did was search for "kf6" and install _every_ single kf6-related package that was missing. 

Building worked afterwards.

**Comment by taj-ny** [comment]
All of the required dependencies for openSUSE can now be found in the README.
