### ISSUE TITLE
Floating panel blur area too large

### ISSUE THREAD

**Issue by bradrjohns** [taj-ny/kwin-effects-forceblur#24]
Around floating panels, the blur region extends too far by maybe 10 pixels and is rectangular in shape
![Screenshot_20240319_160837](https://github.com/taj-ny/kwin-forceblur/assets/163456434/a5311dd1-8f52-40b5-8b0a-41ca567022e1)
![Screenshot_20240319_160815](https://github.com/taj-ny/kwin-forceblur/assets/163456434/e601f660-1748-4c9b-8d77-7f762c7427b1)

**Comment by taj-ny** [comment]
Floating panels have an invisible border that is part of the window. I don't think there's a way to fix this. Why do you need to blur plasmashell?

**Comment by bradrjohns** [comment]
I have plasmashell windows set to 100% opacity currently, and the larger blur region is still present around the panels. Not sure if there is a setting I am missing other than window rules that could be force blurring plasmashell? I also tried non-blur plasma styles but that didn't have an effect. 

With the default KDE blur effect (see attached), I am not seeing the issue though:
![Screenshot_20240319_165231](https://github.com/taj-ny/kwin-forceblur/assets/163456434/8f822ce7-7bc4-4828-bb8d-b5dd05269c6d)

PS- really appreciate all the work you've done with this!

**Comment by queenbiscuit311** [comment]
I don't seem to have this at all. Maybe something weird with your configuration or theme?

![image](https://github.com/taj-ny/kwin-forceblur/assets/88851292/9cee4fdd-eacb-4fbe-ac97-df5f6ae8d795)

![image](https://github.com/taj-ny/kwin-forceblur/assets/88851292/08bee39d-675e-477f-a6e2-4d18108dd5c8)

**Comment by taj-ny** [comment]
@bradrjohns Send a screenshot of the force blur effect configuration.

**Comment by bradrjohns** [comment]
I went to take a screenshot, and realized I had previously toggled on "blur all except matching" and did include plasmashell as an exception. When I added plasmashell, the larger blur region was no longer an issue. The only downside is now I don't have blur for plasmashell menus or windows, but that is very minor.
![image](https://github.com/taj-ny/kwin-forceblur/assets/163456434/9a325e96-0cef-4a07-8a4f-a8b4f73e8904)

**Comment by taj-ny** [comment]
> The only downside is now I don't have blur for plasmashell menus or windows, but that is very minor.
This won't be an issue anymore when #25 is implemented. It'll also include the option to only match certain window types.

**Comment by taj-ny** [comment]
Since docks don't need to be forcefully blurred, I disabled that on the ``develop`` branch.

**Comment by taj-ny** [comment]
Fixed in v1.1.2.
