### ISSUE TITLE
Question about the blur effect

### ISSUE THREAD

**Issue by bouteillerAlan** [taj-ny/kwin-effects-forceblur#27]
Hello, when you said "Disable the Blur effect" you talk about the default one in the desktops effects section of the System Settings ? And why we have to do that ?

![image](https://github.com/taj-ny/kwin-effects-forceblur/assets/30547569/b778cb0c-993a-4799-a5c4-7d69ae0a45c9)

**Comment by queenbiscuit311** [comment]
The blur itself in this extension is a fork of the blur effect already present in plasma. You do indeed have to disable it because otherwise you'd just have two of the same blur effect on at once for every non-force-blurred window which would be a problem.

**Comment by bouteillerAlan** [comment]
Ok thanks you for the information :)
