### ISSUE TITLE
Installation filed after system upgrade.

### ISSUE THREAD

**Issue by Draguljche** [taj-ny/kwin-effects-forceblur#31]
After update I tried to rebuild forceblur and got this errpors:

[ErrorLog.txt](https://github.com/taj-ny/kwin-effects-forceblur/files/14774361/ErrorLog.txt)

- OS: Rosa Linux Fresh v13.0, platform 2023.1
- Plasma Version: v6.0.3
- Kernel: v6.6.22-generic-2rosa2023.1-x86_64

Please, If someone can help?

**Comment by taj-ny** [comment]
Have you tried doing what the warning message suggests?
```bash
sudo dnf --refresh install "/usr/lib64/libkwin.so.6.0.2"
```
