### ISSUE TITLE
Using the "Blur all except matching" option blurs the entire screen when using Spectacle's screen recording

### ISSUE THREAD

**Issue by Haraven** [taj-ny/kwin-effects-forceblur#35]
## Description

If you use the "Blur all except matching" option in Force Blur's settings, the entire screen gets blurred when trying to record a region of the screen with Spectacle. This is specifically tied to recording a screen region with Spectacle. It doesn't happen when taking screenshots and it doesn't happen if doing a whole screen recording.

**N.b.**: Spectacle's screen recording functionality is only available under Wayland.

I did try to add Spectacle's window class (`org.kde.spectacle`) to Force Blur's exceptions. That makes it so the blur doesn't start when you're selecting the region to record. But as soon as you start recording, the screen gets blurred. It goes away as soon as you stop.

## Steps to reproduce

1. Use a Plasma Wayland session
2. Install Spectacle
3. Install Force Blur
4. Configure Force Blur to use the "blur all except matching" option
5. Optionally, add `org.kde.spectacle` to the list of exceptions
6. Start screen recording (I used key combos: SUPER + SHIFT + R or SUPER + R)
7. Select a screen region to record
8. Press enter to start recording
9. Watch as the screen gets blurred (to cancel, you have to stop recording by repeating the above key combo)

## Settings used

![screenshot_08-04-2024_17-05-53](https://github.com/taj-ny/kwin-effects-forceblur/assets/10146027/e174bcf5-b42e-45c1-8f75-0b8d91c9033d)

## OS information
- Plasma version: 6.0.3
- Force Blur version: latest git (commit b6a43892c6686ebebb7509ac61eb18c8077e4a66)

**Comment by taj-ny** [comment]
The class of Spectacle's recording window is ``spectacle``. I'll add an option to log all window classes to make it easier for users to find them in cases like this one.

**Comment by Haraven** [comment]
> The class of Spectacle's recording window is `spectacle`. I'll add an option to log all window classes to make it easier for users to find them in cases like this one.

Thanks very much! I couldn't for the life of me figure out what the recording window class was. I tried the method you have in the repo readme (`qdbus ...`), but it always bypassed Spectacle's window and selected whatever was underneath, when recording.

I can confirm that by adding `spectacle` to Force Blur's exceptions, the screen no longer gets blurred.

**Comment by taj-ny** [comment]
- #36
