### ISSUE TITLE
Konsole background blurring broken

### ISSUE THREAD

**Issue by steviator** [taj-ny/kwin-effects-forceblur#37]
Konsole background blurring doesn't work properly when using this plugin, it puts an ugly black border several pixels thick around the content area, making it look worse than the proverbial dog's allegorical breakfast.

For me at least, this plugin is unusable if it breaks Konsole. 

![hideous](https://github.com/taj-ny/kwin-effects-forceblur/assets/12746873/ec4a868b-775b-465b-993a-9ea6b794c933)

**Comment by taj-ny** [comment]
The border is not added by this effect. It's present even when the blur effect is disabled.

![image](https://github.com/taj-ny/kwin-effects-forceblur/assets/79316397/5db85250-b6bf-4ec1-8b0e-acdc1d4604a5)

It seems to be an issue with Breeze, as the border is not present with shadows disabled.

![image](https://github.com/taj-ny/kwin-effects-forceblur/assets/79316397/7e9bf360-12c7-4e92-bd74-82a6c8ef1ab7)
