### ISSUE TITLE
Effect stopped working after updating Plasma

### ISSUE THREAD

**Issue by taj-ny** [taj-ny/kwin-effects-forceblur#52]
KWin effects have to be rebuilt after updating Plasma.

**Comment by Susanthakuri92** [comment]
yes same using kde, is there a fix?

**Comment by Kayzels** [comment]
> yes same using kde, is there a fix?

When you update Plasma, you need to rebuild this. That 's what the issue is saying. It will always break after a Plasma update, so you need to delete the build folder and rebuild it.

**Comment by taj-ny** [comment]
> yes same using kde, is there a fix?

I forgot to respond but if you're using the AUR package you'll also need to cleanBuild.
