### ISSUE TITLE
OpenSUSE Tumbleweed: Force Blur no longer works

### ISSUE THREAD

**Issue by Haraven** [taj-ny/kwin-effects-forceblur#53]
**Describe the bug**
As of today, after updating my system, the Force Blur desktop effect is no longer applied and doesn't show up under Desktop Effects anymore.

I've tried rebooting. I've also tried reinstalling by deleting these 2 files:
- `/usr/lib64/qt6/plugins/kwin/effects/configs/kwin_forceblur_config.so`
- `/usr/lib64/qt6/plugins/kwin/effects/plugins/forceblur.so`

rebuilding the source, and then reinstalling using the steps in the readme. The effect still doesn't show up.

**To Reproduce**
1. Install OpenSUSE Tumbleweed
2. Update it (`sudo zypper refresh && sudo zypper dup`). Restart if zypper recommends it
4. Download the `kwin-effects-forceblur` source, compile it and install it (see [this](https://github.com/taj-ny/kwin-effects-forceblur/issues/20) for needed dependencies)
5. Try to find the effect under Desktop Effects - it should be missing

**Expected behavior**
The effect should be enabled and available under Desktop Effects.

**System information**
- OS: OpenSUSE Tumbleweed
- Plasma version: 6.0.4
- Kwin-effects-forceblur version: latest git (v1.2.0)

**Comment by taj-ny** [comment]
Can't reproduce. Works for me on a fresh installation.
![image](https://github.com/taj-ny/kwin-effects-forceblur/assets/79316397/da31335f-6ae1-4daf-9c5d-5f1df75214b3)

While trying to figure out what packages I needed to install, I noticed that I had to delete the whole build directory, otherwise it would throw linker errors. Maybe try doing that?

**Comment by Haraven** [comment]
I can confirm that deleting the build directory and then running the installation steps again worked.

In case anyone else runs into this issue, don't forget to restart after reinstalling kwin-effects-forceblur :)

I'll close this issue now.

Thank you!
