### ISSUE TITLE
Add instructions for installing dependencies on some distributions

### ISSUE THREAD

**Issue by taj-ny** [taj-ny/kwin-effects-forceblur#55]
- [x] Arch Linux
- [x] Fedora
- [x] openSUSE
- [ ] Debian-based

**Comment by D3SOX** [comment]
For a working configuration on Arch you can take them from [my AUR package PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kwin-effects-forceblur):

```bash
depends=(kio knotifications kwin kcrash kglobalaccel)
makedepends=(git extra-cmake-modules qt6-tools)
```

**Comment by AngelSherry** [comment]
I maintain the SPEC file of RPM of kwin-effects-forceblur on [my COPR repository](https://copr.fedorainfracloud.org/coprs/yohane-shiro/kwin-effects-forceblur/) on Nobara 39, which is already updated to Plasma 6 for a while.  There should be the same requires on Fedora 40 on Plasma 6.

```
BuildRequires: kf6-kwindowsystem-devel plasma-workspace-devel libplasma-devel qt6-qtbase-private-devel qt6-qtbase-devel cmake kwin-devel extra-cmake-modules kwin-devel kf6-knotifications-devel kf6-kio-devel kf6-kcrash-devel kf6-ki18n-devel kf6-kguiaddons-devel libepoxy-devel kf6-kglobalaccel-devel kf6-kcmutils-devel kf6-kconfigwidgets-devel kf6-kdeclarative-devel kdecoration-devel
Requires: kf6-kglobalaccel kf6-kdeclarative kwin libplasma kf6-kio qt6-qtbase kf6-kguiaddons kf6-ki18n
```
