### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by kevaldonga** [taj-ny/kwin-effects-forceblur#69]
This error is shown when trying to build it with cmake.

`-- Could NOT find KF6KCMUtils (found version "6.2.0"), checked the following files:
    /usr/lib/cmake/KF6KCMUtils/KF6KCMUtilsConfig.cmake (version 6.2.0)
    Reason given by package: KF6KCMUtils could not be found because dependency KF6CoreAddons could not be found.
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF6 (missing: KIO Service Service KCMUtils) (found suitable
  version "6.0.0", minimum required is "5.240.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF6.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:42 (find_package)`

**Comment by taj-ny** [comment]
What distribution are you using?

**Comment by kevaldonga** [comment]
umm kde ? does kwin run on other distros too ?

**Comment by D3SOX** [comment]
KDE is not a distribution. Try sending the output of `cat /etc/os-release`

**Comment by kevaldonga** [comment]
oh sorry, I use arch

**Comment by taj-ny** [comment]
Did you run the command from the README to install dependencies? If so, try also installing ``kcrash kglobalaccel kio knotifications``. I thought these packages would be installed since they're dependencies of *plasma-meta*, but I may have been wrong.

You can also just use the [AUR package](https://aur.archlinux.org/packages/kwin-effects-forceblur).

**Comment by kevaldonga** [comment]
I did installed them but issue remains the same.

**Comment by D3SOX** [comment]
Maybe you need to install `kcoreaddons`

**Comment by kevaldonga** [comment]
all of these packages having conflict with their git version *-git. which one should I keep ?

**Comment by kevaldonga** [comment]
`
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF6 (missing: KIO Service Service KCMUtils) (found suitable
  version "6.0.0", minimum required is "5.240.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF6.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:42 (find_package)
`
now this error it found that package unsuitable

**Comment by kevaldonga** [comment]
which package is it pointing at ?

**Comment by D3SOX** [comment]
Don't use KDE git packages at all

**Comment by kevaldonga** [comment]
I dont think the issue is on my side 
https://discuss.kde.org/t/cmake-complain-about-missing-kf6plasma/8675/2

**Comment by iLostMyXbox21** [comment]
did you make sure to run

sudo pacman -S base-devel git extra-cmake-modules qt6-tools

im using arch as well and didnt run into any of those issues

**Comment by kevaldonga** [comment]
I am switching to hyprland. closing this now as it's still not resolved.
