### ISSUE TITLE
After updating kde no forceblur appears in system effects

### ISSUE THREAD

**Issue by pwn27sbx** [taj-ny/kwin-effects-forceblur#97]
try reinstalling but apparently something broke with the kde update.

**Comment by pwn27sbx** [comment]
already fixed it :)

**Comment by wlh320** [comment]
I've encountered the same problem. Could you tell me how you fixed it?

**Comment by taj-ny** [comment]
#52

**Comment by wlh320** [comment]
I've tried to reinstall from an unofficial Arch repo before, and it did not work. I then tried to reinstall from AUR directly, it works.
Thank you!

**Comment by ShayBox** [comment]
Should this not be a pacman hook?
